<template>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
  <div>switch</div>
</template>
<script lang="ts"></script>
<style lang="scss" scoped></style>
